"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-wg7at9%docnn!u(-lrhpt7tj12cvar!-a!0ltjx%q*9x+4&$g^'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
ALLOWED_HOSTS = ['*']  # for testing


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'accounts',
    'jobs'
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]/* Reset */
body {
    font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
    margin: 0;
    padding: 0;
    background-color: #f7f9fc;
    color: #333;
}

nav {
    background-color: #1f2937;
    padding: 12px 20px;
}

nav a {
    color: #fff;
    margin-right: 20px;
    text-decoration: none;
    font-weight: bold;
}

nav a:hover {
    color: #60a5fa;
}

.hero {
    text-align: center;
    padding: 80px 20px;
    background: linear-gradient(90deg, #60a5fa, #3b82f6);
    color: white;
}

.hero h1 {
    font-size: 3rem;
    margin-bottom: 15px;
}

.hero p {
    font-size: 1.2rem;
    margin-bottom: 25px;
}

.hero .btn {
    padding: 12px 25px;
    margin: 5px;
    border-radius: 6px;
    text-decoration: none;
    font-weight: bold;
    transition: 0.3s;
}
/* Reset */
body {
    font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
    margin: 0;
    padding: 0;
    background-color: #f7f9fc;
    color: #333;
}

nav {
    background-color: #1f2937;
    padding: 12px 20px;
}

nav a {
    color: #fff;
    margin-right: 20px;
    text-decoration: none;
    font-weight: bold;
}

nav a:hover {
    color: #60a5fa;
}

.hero {
    text-align: center;
    padding: 80px 20px;
    background: linear-gradient(90deg, #60a5fa, #3b82f6);
    color: white;
}

.hero h1 {
    font-size: 3rem;
    margin-bottom: 15px;
}

.hero p {
    font-size: 1.2rem;
    margin-bottom: 25px;
}

.hero .btn {
    padding: 12px 25px;
    margin: 5px;
    border-radius: 6px;
    text-decoration: none;
    font-weight: bold;
    transition: 0.3s;
}

.hero .btn:hover {
    opacity: 0.9;
}

.hero .btn-primary {
    background-color: #1f2937;
    color: white;
}

.hero .btn {
    background-color: white;
    color: #1f2937;
}

.section-title {
    text-align: center;
    font-size: 2rem;
    margin: 40px 0 20px 0;
    color: #1f2937;
}

.job-container {
    display: flex;
    flex-wrap: wrap;
    justify-content: center;
    gap: 20px;
    padding-bottom: 50px;
}

.job-card {
    background-color: white;
    padding: 20px;
    width: 260px;
    border-radius: 10px;
    box-shadow: 0 4px 12px rgba(0,0,0,0.1);
    transition: transform 0.2s;
}

.job-card:hover {
    transform: translateY(-5px);/* Reset */
body {
    font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
    margin: 0;
    padding: 0;
    background-color: #f7f9fc;
    color: #333;
}

nav {
    background-color: #1f2937;
    padding: 12px 20px;
}

nav a {
    color: #fff;
    margin-right: 20px;
    text-decoration: none;
    font-weight: bold;
}

nav a:hover {
    color: #60a5fa;
}

.hero {
    text-align: center;
    padding: 80px 20px;
    background: linear-gradient(90deg, #60a5fa, #3b82f6);
    color: white;
}

.hero h1 {
    font-size: 3rem;
    margin-bottom: 15px;
}

.hero p {
    font-size: 1.2rem;
    margin-bottom: 25px;
}

.hero .btn {
    padding: 12px 25px;
    margin: 5px;
    border-radius: 6px;
    text-decoration: none;
    font-weight: bold;
    transition: 0.3s;
}

.hero .btn:hover {
    opacity: 0.9;
}

.hero .btn-primary {
    background-color: #1f2937;
    color: white;
}

.hero .btn {
    background-color: white;
    color: #1f2937;
}

.section-title {
    text-align: center;
    font-size: 2rem;
    margin: 40px 0 20px 0;
    color: #1f2937;
}

.job-container {
    display: flex;
    flex-wrap: wrap;
    justify-content: center;
    gap: 20px;
    padding-bottom: 50px;
}

.job-card {
    background-color: white;
    padding: 20px;
    width: 260px;
    border-radius: 10px;
    box-shadow: 0 4px 12px rgba(0,0,0,0.1);
    transition: transform 0.2s;
}

.job-card:hover {
    transform: translateY(-5px);
}

.job-card h3 {
    margin-top: 0;
    font-size: 1.2rem;
    color: #111827;
}

.job-card a {
    color: #3b82f6;
    font-weight: bold;
    text-decoration: none;
}

.job-card a:hover {
    text-decoration: underline;
}

}

.job-card h3 {
    margin-top: 0;
    font-size: 1.2rem;
    color: #111827;
}

.job-card a {
    color: #3b82f6;
    font-weight: bold;
    text-decoration: none;
}

.job-card a:hover {
    text-decoration: underline;
}

.hero .btn:hover {
    opacity: 0.9;
}

.hero .btn-primary {
    background-color: #1f2937;
    color: white;
}

.hero .btn {
    background-color: white;
    color: #1f2937;
}

.section-title {
    text-align: center;
    font-size: 2rem;
    margin: 40px 0 20px 0;
    color: #1f2937;
}

.job-container {
    display: flex;
    flex-wrap: wrap;
    justify-content: center;
    gap: 20px;
    padding-bottom: 50px;
}

.job-card {
    background-color: white;
    padding: 20px;
    width: 260px;
    border-radius: 10px;
    box-shadow: 0 4px 12px rgba(0,0,0,0.1);
    transition: transform 0.2s;
}

.job-card:hover {
    transform: translateY(-5px);
}

.job-card h3 {
    margin-top: 0;
    font-size: 1.2rem;
    color: #111827;
}

.job-card a {
    color: #3b82f6;
    font-weight: bold;
    text-decoration: none;
}

.job-card a:hover {
    text-decoration: underline;
}



ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # 'DIRS': [],
        'DIRS': [os.path.join(BASE_DIR, 'templates')],  # <-- add this
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / "staticfiles"

STATICFILES_DIRS = [
    BASE_DIR / "static",  # BASE_DIR is your project root
]
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"
# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'accounts.User' #This line is critical. It tells Django: “Stop using the default user. Use my custom one instead.”

